// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using serieshue.Models;

#nullable disable

namespace serieshue.Migrations
{
    [DbContext(typeof(SeriesHueContext))]
    partial class SeriesHueContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("serieshue.Models.Episode", b =>
                {
                    b.Property<string>("TConst")
                        .HasColumnType("text");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<string>("EpisodeTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<string>("TitleTconst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Votes")
                        .HasColumnType("integer");

                    b.HasKey("TConst");

                    b.HasIndex("TitleTconst");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("serieshue.Models.Title", b =>
                {
                    b.Property<string>("Tconst")
                        .HasColumnType("text");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer");

                    b.Property<string>("Genres")
                        .HasColumnType("text");

                    b.Property<bool?>("IsAdult")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryTitle")
                        .HasColumnType("text");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("StartYear")
                        .HasColumnType("integer");

                    b.HasKey("Tconst");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("serieshue.Models.Episode", b =>
                {
                    b.HasOne("serieshue.Models.Title", "Title")
                        .WithMany("Episodes")
                        .HasForeignKey("TitleTconst")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("serieshue.Models.Title", b =>
                {
                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
